{{ if and .Values.obank.enabled (not .Values.obank.existingSecret ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-obank
  labels:
{{ include "psd2.labels" . | indent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.obank.existingSecret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
