{{- if and .Values.xs2a.enabled (not .Values.xs2a.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-xs2a
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: xs2a
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: {{ .Values.xs2a.image.name }}:{{ .Values.xs2a.image.tag }}
    referencePolicy:
        type: Source
{{- end }}
