---
language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "adorsys"
    token: ${SONAR_TOKEN}

git:
  submodules: false

install:
  - mvn --version

before_script:
  - mvn --version
  - echo "TRAVIS_JDK_VERSION is $TRAVIS_JDK_VERSION"

script:
  # add travis build id to swagger
  - env BUILD_NUMBER=$TRAVIS_BUILD_ID /bin/bash ./scripts/set_xs2a_connector_version_in_swagger.sh
  # check code by pmd
  - mvn -ntp -V -DskipITs -DskipTests clean install pmd:pmd pmd:cpd | egrep -A2 -B2 "(Building|SUCCESS|ERROR)" || travis_terminate 1
  # check UNIT tests
  - mvn -ntp -DskipITs --fail-at-end clean install -q | egrep -A2 -B2 "(Building|SUCCESS|ERROR)" || travis_terminate 1
  # check IT tests
  - mvn -ntp failsafe:integration-test failsafe:verify | egrep -A2 -B2 "(Building|SUCCESS|ERROR)" || travis_terminate 1
  # JavaDocs are broken in Java 11 and fixed only in Java 12 : https://bugs.openjdk.java.net/browse/JDK-8212233
  - mvn -ntp -V -DskipITs -DskipTests javadoc:javadoc | egrep -A2 -B2 "(Building|SUCCESS|ERROR)" || travis_terminate 1
  # Sonar analysis shall be run only for one version of Java
  - mvn -ntp -V -DskipITs -DskipTests sonar:sonar -Dsonar.projectKey=adorsys_xs2a | egrep -A2 -B2 "(Building|SUCCESS|ERROR)" || travis_terminate 1
  - docker run -it --rm -v $PWD:/src -w /src -u $(id -u ${USER}):$(id -g ${USER}) adorsys/arc42-tools
    sh -c "make pages" || travis_terminate 1

before_deploy:
  - gpg --version
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || true

deploy:
  - skip_cleanup: true
    provider: script
    script: mvn -ntp --settings scripts/mvn-release-settings.xml -Prelease -DskipTests  -DskipTests -B
      -U deploy | egrep -A2 -B2 "(Building|SUCCESS|ERROR|Uploaded)" || travis_terminate 1
    on:
      repo: adorsys/xs2a
      all_branches: true
      condition: |-
        ( ( $TRAVIS_TAG =~ ^([[:digit:]]+\.)+[[:digit:]]+(-(RC)?[[:digit:]]+)?([\.-]([[:digit:]]+\.)+[[:digit:]]+(-[[:digit:]]+)?)?$
          || "$TRAVIS_BRANCH" = "develop" )
        && "$TRAVIS_JDK_VERSION" = "openjdk11" )
  - provider: pages
    skip_cleanup: true
    github-token: "$GITHUB_PAGES_TOKEN"
    keep-history: false
    local-dir: pages/html
    on:
      branch: develop
      condition: ( "$TRAVIS_JDK_VERSION" = "openjdk11" )
