---
xs2a:
  enabled: true
  image:
    name: xs2a-integtests
    tag: latest
    namespace: adorsys-psd2-develop
    stream: true

cms:
  enabled: true
  image:
    name: xs2a-aspsp-cms
    namespace: adorsys-psd2-develop
    stream: true

aspsp:
  enabled: true
  image:
    name: xs2a-aspsp-profile
    namespace: adorsys-psd2-develop
    stream: true

mock:
  enabled: true
  image:
    name: aspsp-mock-server
    namespace: adorsys-psd2-develop
    stream: true

keycloak:
  dbVendor: h2
