{{ if .Values.uiapp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{- with .Values.uiapp.deploymentAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
    image.openshift.io/triggers: |
      [{
        "from": {
          "kind": "ImageStreamTag",
          "name":"{{- if .Values.uiapp.image.stream }}{{ .Values.uiapp.image.name }}:{{ default "latest" .Values.uiapp.image.tag }}{{- else }}{{ template "psd2.fullname" . }}-uiapp:latest{{- end }}"
        },
        "fieldPath": "spec.template.spec.containers[?(@.name==\"uiapp\")].image"
      }]
    checksum/secret: {{ include (print $.Template.BasePath "/uiapp/uiapp-secret.yaml") . | sha256sum }}
  name: {{ template "psd2.fullname" . }}-uiapp
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: uiapp
    app: uiapp
spec:
  serviceName: {{ template "psd2.fullname" . }}-uiapp
  replicas: {{ .Values.uiapp.replicas }}
  selector:
    matchLabels:
{{ include "psd2.matchLabels" . | indent 6 }}
      component: uiapp
  template:
    metadata:
    {{- if .Values.uiapp.podAnnotations }}
      annotations:
{{ toYaml .Values.uiapp.podAnnotations | indent 8 }}
    {{- end }}
      labels:
{{ include "psd2.matchLabels" . | indent 8 }}
        component: uiapp
    spec:
      containers:
        - name: uiapp
          image: " "
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  key: uiapp
                  name: "{{ template "psd2.fullname" . }}-keycloak"
{{- range $name, $value := .Values.uiapp.env }}
{{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ tpl (toString $value) $ | quote }}
{{- end }}
{{- end }}
{{- with .Values.extraEnv }}
{{ tpl . $ | indent 8 }}
{{- end }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
          resources:
{{ toYaml .Values.uiapp.resources | indent 12 }}
{{- end }}
