{{ if and .Values.uiapp.enabled .Values.uiapp.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "psd2.fullname" . }}-uiapp
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: uiapp
spec:
{{- if .Values.uiapp.route.host }}
  host: {{ . | quote }}
{{- end }}
  port:
    targetPort: http
{{- with .Values.uiapp.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-uiapp
    weight: 100
    wildcardPolicy: None
{{- end }}
