{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-keycloak-init
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: keycloak-init
stringData:
  init.sh: |
    #!/usr/bin/env bash

    if ! timeout 60 sh -c "until printf '.' && timeout 1 sh -c 'cat < /dev/null > /dev/tcp/"$(echo "${KEYCLOAK_HOST##*/}" | tr ':' '/')"'; do sleep 2; done"; then
      echo "Can not reach ${KEYCLOAK_HOST}"
    fi

    echo

    {{- range $name, $config := .Values.keycloak.realms }}
    {{- if not (empty $config) }}
    REALM_NAME={{ $name | quote }}
    REALM='{
      "realm": "'${REALM_NAME}'",
      "enabled": true,
      {{- with $config.registrationAllowed }}
      "registrationAllowed": {{ . }},
      {{- end }}
      {{- if not (empty $config.smtpServer) }}
      "smtpServer": {
        "host": {{ tpl $config.smtpServer.host $ | quote }},
        "from": {{ tpl $config.smtpServer.from $ | quote }}
      },
      {{- end }}
      "displayName": {{ default $name $config.displayName | quote }}{{- with $config.clients }},
      "clients": [
      {{- $lastClientName := . | keys | sortAlpha | last }}
      {{- range $clientName, $clientConfig := . }}
        {
          "clientId": {{ $clientName | quote }},
          "name": {{ $clientName | quote }},
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": {{ tpl $clientConfig.secret $ | quote }},
          "redirectUris": {{- if empty $clientConfig.redirectUris }}["*"]{{- else }}{{ $clientConfig.redirectUris | toJson }}{{- end }},
          "webOrigins": {{- if empty $clientConfig.webOrigins }}["*"]{{- else }}{{ $clientConfig.webOrigins | toJson }}{{- end }},
          "standardFlowEnabled": {{ default true $clientConfig.standardFlowEnabled }},
          "implicitFlowEnabled": {{ default false $clientConfig.implicitFlowEnabled }},
          "directAccessGrantsEnabled": {{ default true $clientConfig.directAccessGrantsEnabled }},
          "serviceAccountsEnabled": {{ default true $clientConfig.serviceAccountsEnabled }},
          "authorizationServicesEnabled": {{ default true $clientConfig.authorizationServicesEnabled }}
        }{{ if not (eq $lastClientName $clientName) }},{{ end }}
      {{- end }}
      ]
      {{- end }}{{- with $config.users }},
      "users": [
      {{- $lastUserName := . | keys | sortAlpha | last }}
      {{- range $userName, $userConfig := . }}
        {
          "enabled": true,
          "username": {{ $userName | quote }},
          "firstName": {{ $userConfig.firstName | quote }},
          "lastName": {{ $userConfig.lastName | quote }},
          "email": {{ $userConfig.email | quote }},
          "credentials": {{ $userConfig.credentials | toJson }}
        }{{ if not (eq $lastUserName $userName) }},{{ end }}
      {{- end }}
      ]
      {{- end }}
    }'

    # https://www.keycloak.org/docs/1.9/server_development_guide/topics/admin-rest-api.html
    if ! TOKEN=$(curl -sSf -d "client_id=admin-cli" -d "username=admin" -d "password=admin" -d "grant_type=password" "${KEYCLOAK_HOST}/auth/realms/master/protocol/openid-connect/token" | jq -r .access_token); then
      echo "Error while getting admin token."
      echo "${TOKEN}"
      exit 1
    fi

    # https://www.keycloak.org/docs-api/3.0/rest-api/index.html
    if [ "404" == "$(curl -w "%{http_code}" -o /dev/null -sS -H "Authorization: Bearer ${TOKEN}" "${KEYCLOAK_HOST}/auth/admin/realms/${REALM_NAME}" --header "Content-Type: application/json")" ]; then
      if ! API_RETURN=$(curl -sSf -H "Authorization: Bearer ${TOKEN}" "${KEYCLOAK_HOST}/auth/admin/realms" --header "Content-Type: application/json" --data "${REALM}"); then
        echo "Error while create realm."
        echo "${API_RETURN}"
        exit 1
      fi
      echo "Creating ${REALM_NAME} was successful!"
    else
      if ! API_RETURN=$(curl -sSf -H "Authorization: Bearer ${TOKEN}" "${KEYCLOAK_HOST}/auth/admin/realms/${REALM_NAME}" --header "Content-Type: application/json" -XPUT --data "${REALM}"); then
        echo "Error while update realm."
        echo "${API_RETURN}"
        exit 1
      fi
      echo "Updating ${REALM_NAME} was successful!"
    fi

    {{- end }}
    {{- end }}
{{- end }}
