{{ if and .Values.obank.enabled .Values.obank.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "psd2.fullname" . }}-obank
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: OnlineBanking
spec:
  host: {{ tpl (required "obank.route.host must be defined" .Values.obank.route.host) . | quote }}
  port:
    targetPort: http
{{- with .Values.obank.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-obank
    weight: 100
    wildcardPolicy: None
{{- end }}
