{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-keycloak
  labels:
{{ include "psd2.labels" . | indent 4 }}
type: Opaque
data:
  admin-username: "{{ tpl .Values.keycloak.admin.username $ | b64enc }}"
  admin-password: "{{ tpl .Values.keycloak.admin.password $ | b64enc }}"
{{- range $name, $value := .Values.keycloak.secrets }}
{{- if not ( empty $value) }}
  {{ $name }}: {{ tpl (toString $value) $ | b64enc | quote }}
{{- end }}
{{- end }}
{{- if (eq .Values.keycloak.dbVendor "postgres") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-keycloak-db
  labels:
{{ include "psd2.labels" . | indent 4 }}
type: Opaque
data:
  admin-password: "{{ tpl .Values.keycloak.admin.password $ | b64enc }}"
  username: "{{ tpl .Values.keycloak.db.user.username $ | b64enc }}"
  password: "{{ tpl .Values.keycloak.db.user.password $ | b64enc }}"
  database: "{{ tpl .Values.keycloak.db.database.name $ | b64enc }}"
{{- end }}
{{- end }}
