{{- if and .Values.cms.enabled (eq .Values.keycloak.dbVendor "postgres") (not .Values.postgres.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-pg-db
  labels:
{{ include "psd2.labels" . | indent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
    referencePolicy:
      type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- if and .Values.postgres.metrics.enabled (not .Values.postgres.metrics.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-pg-metrics
  labels:
{{ include "psd2.labels" . | indent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: {{ .Values.postgres.metrics.image.name }}:{{ .Values.postgres.metrics.image.tag }}
    referencePolicy:
      type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- end }}
{{- end }}
