{{- if and .Values.cms.enabled (eq .Values.keycloak.dbVendor "postgres") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-pg-db
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: pg-db
type: Opaque
data:
  {{- range $name, $value := .Values.postgres.secrets }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ tpl (toString $value) $ | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
