name: test CI

on: 
  push:
    branches:
      - KOA_add_github_pages_to_actions

env:
  SONAR_PRJ_KEY: adorsys_xs2a
  SONAR_ORG: adorsys
  SONAR_HOST: https://sonarcloud.io
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  test_github_actions:
    name: create github pages
    runs-on: ubuntu-latest
    steps:
      - name: Clone XS2A develop repository
        uses: actions/checkout@v2

      - name: install Make plantuml asciidoctor
        run: sudo apt-get update && sudo apt-get install make plantuml rsync tree -y

      - name: prepare pages and diagramms
        run: | 
            mkdir -p pages/html/doc
            rsync -armR --include="*/" --include="*."{adoc,puml,png} --exclude="*" doc/ pages
            cd pages/doc
            plantuml **/*.puml -DPLANTUML_LIMIT_SIZE=8192

      - name:  Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install AsciiDoctor
        uses: reitzig/actions-asciidoctor@v1.0.0

      - name: Convert adoc to html
        run: ls -lh && cd ../ && asciidoctor --failure-level WARN -R doc -D html '**/*.adoc'

      - name: Rsync diagrams and pictures
        run: cd doc && rsync -amvR --include="*/" --include="*.png" --exclude="*" . ../html

      - name: check pages html tree
        run: cd ../ && rm -rf doc && tree html && ls -lh .
