name: Develop pull-request CI

on: 
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    name: Build and test XS2A (openjdk 1.11)
    runs-on: ubuntu-latest
    steps:
      - name: Clone XS2A develop repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build XS2A
        run: mvn -ntp -DskipTests -DskipITs -Dmaven.javadoc.skip=true clean install

      - name: Check pmd  
        run: mvn -ntp pmd:check

      - name: Generate javadocs 
        run: mvn -ntp javadoc:javadoc

      - name: Run UI tests 
        run: mvn -ntp -DskipITs --fail-at-end clean install

      - name: Run IT tests 
        run: mvn -ntp failsafe:integration-test failsafe:verify 

